# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GIS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Parse'
pod 'GZIP'
pod 'DateTools'
  # Pods for GIS

  target 'GISTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GISUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
